<?php

  $categories_array = array(
     array( 'gruppo' => 'figurini', "sigla" => 'HSP', 'it' =>	'Storico standard pittura', 'en' =>	'Historical standard painting', 'needs_display' => true),
     array( 'gruppo' => 'FIGURINI', "sigla" => 'HSO', 'it' =>	'Storico standard open', 'en' =>	'Historical standard open', 'needs_display' => true),
     array( 'gruppo' => 'FIGURINI', "sigla" => 'HMP', 'it' =>	'Storico master pittura', 'en' =>	'Historical master painting', 'needs_display' => true),
     array( 'gruppo' => 'FIGURINI', "sigla" => 'HMO', 'it' =>	'Storico master open', 'en' =>	'Historical master open', 'needs_display' => true),
     array( 'gruppo' => 'FIGURINI', "sigla" => 'FSP', 'it' =>	'Fantasy standard pittura', 'en' =>	'Fantasy standard painting', 'needs_display' => true),
     array( 'gruppo' => 'FIGURINI', "sigla" => 'FSO', 'it' =>	'Fantasy standard open', 'en' =>	'Fantasy standard open', 'needs_display' => true),
     array( 'gruppo' => 'FIGURINI', "sigla" => 'FMP', 'it' =>	'Fantasy master pittura', 'en' =>	'Fantasy master painting', 'needs_display' => true),
     array( 'gruppo' => 'FIGURINI', "sigla" => 'FMO', 'it' =>	'Fantasy master open', 'en' =>	'Fantasy master open', 'needs_display' => true),
     array( 'gruppo' => 'ORDNANCE', "sigla" => 'AS1', 'it' =>	'Aerei ed Elicotteri standard 1/72', 'en' =>	'Planes and choppers standard 1/72'),
     array( 'gruppo' => 'ORDNANCE', "sigla" => 'AS2', 'it' =>	'Aerei ed Elicotteri standard 1/48–1/32–1/35', 'en' =>	'Planes and choppers standard 1/48–1/32–1/35'),
     array( 'gruppo' => 'ORDNANCE', "sigla" => 'ASD1', 'it' =>	'Diorami areonautici standard 1/72', 'en' =>	'Aerospace dioramas standard 1/72'),
     array( 'gruppo' => 'ORDNANCE', "sigla" => 'ASD2', 'it' =>	'Diorami areonautici standard 1/48-1/32-1/35', 'en' =>	'Aerospace dioramas standard 1/48-1/32-1/35'),
     array( 'gruppo' => 'ORDNANCE', "sigla" => 'AM1', 'it' =>	'Aerei ed elicotteri master 1/72', 'en' =>	'Planes and choppers master 1/72'),
     array( 'gruppo' => 'ORDNANCE', "sigla" => 'AM2', 'it' =>	'Aerei ed elicotteri master 1/48-1/32-1/35', 'en' =>	'Planes and choppers master 1/48-1/32-1/35'),
     array( 'gruppo' => 'ORDNANCE', "sigla" => 'AMD1', 'it' =>	'Diorami areonautici master 1/72', 'en' =>	'Aerospace dioramas master 1/72'),
     array( 'gruppo' => 'ORDNANCE', "sigla" => 'AMD2', 'it' =>	'Diorami areonautici master 1/48-1/32-1/35', 'en' =>	'Aerospace dioramas master 1/48-1/32-1/35'),
     array( 'gruppo' => 'ORDNANCE', "sigla" => 'MVS1', 'it' =>	'Veicoli militari standard 1/72-1/48', 'en' =>	'Military vehicles standard 1/72-1/48'),
     array( 'gruppo' => 'ORDNANCE', "sigla" => 'MVS2', 'it' =>	'Veicoli militari standard 1/35', 'en' =>	'Military vehicles standard 1/35'),
     array( 'gruppo' => 'ORDNANCE', "sigla" => 'MVSD1', 'it' =>	'Diorami militari standard 1/72-1/48', 'en' =>	'Military dioramas standard 1/72-1/48'),
     array( 'gruppo' => 'ORDNANCE', "sigla" => 'MVSD2', 'it' =>	'Diorami militari standard 1/35', 'en' =>	'Military dioramas standard 1/35'),
     array( 'gruppo' => 'ORDNANCE', "sigla" => 'MVM1', 'it' =>	'Veicoli militari master 1/72-1/48', 'en' =>	'Military vehicles dioramas master 1/72-1/48'),
     array( 'gruppo' => 'ORDNANCE', "sigla" => 'MVM2', 'it' =>	'Veicoli militari master 1/35', 'en' =>	'Military vehicles master 1/35'),
     array( 'gruppo' => 'ORDNANCE', "sigla" => 'MVMD1', 'it' =>	'Diorami militari master 1/72-1/48', 'en' =>	'Military vechicles dioramas master 1/72-1/48'),
     array( 'gruppo' => 'ORDNANCE', "sigla" => 'MVMD2', 'it' =>	'Diorami militari master 1/35', 'en' =>	'Military vechicles dioramas master 1/35'),
     array( 'gruppo' => 'ORDNANCE', "sigla" => 'N1', 'it' =>	'Navi da scatola tutte le scale', 'en' =>	'Box ships all scales'),
     array( 'gruppo' => 'ORDNANCE', "sigla" => 'N2', 'it' =>	'Navi autocostruite tutte le scale', 'en' =>	'Selfbuilt ships all scales'),
     array( 'gruppo' => 'ORDNANCE', "sigla" => 'ND', 'it' =>	'Diorami navali tutte le scale', 'en' =>	'Naval dioramas all scales'),
     array( 'gruppo' => 'ORDNANCE', "sigla" => 'V1', 'it' =>	'Auto tutte le scale', 'en' =>	'Cars all scales'),
     array( 'gruppo' => 'ORDNANCE', "sigla" => 'V2', 'it' =>	'Moto tutte le scale', 'en' =>	'Motorbikes all scales'),
     array( 'gruppo' => 'ORDNANCE', "sigla" => 'V3', 'it' =>	'Camion e trattori tutte le scale', 'en' =>	'Truck and tractors all scales'),
     array( 'gruppo' => 'ORDNANCE', "sigla" => 'SFS', 'it' =>	'Sci-fi standard', 'en' =>	'Sci-fi standard'),
     array( 'gruppo' => 'ORDNANCE', "sigla" => 'SFM', 'it' =>	'Sci-fi master', 'en' =>	'Sci-fi master'),
     array( 'gruppo' => 'ORDNANCE', "sigla" => 'DSF', 'it' =>	'Diorami sci-fi', 'en' =>	'Dioramas sci-fi'),
     array( 'gruppo' => 'JUNIORES', "sigla" => 'J', 'it' =>	'Juniores', 'en' =>	'Juniores'),
     array( 'gruppo' => 'SPECIAL', "sigla" => 'S', 'it' =>	'Subbuteo contest', 'en' =>	'Subbuteo contest'),
     array( 'gruppo' => 'SPECIAL', "sigla" => 'L', 'it' =>	'Navi in legno contest', 'en' =>	'Wooden ship contest'),
     array( 'gruppo' => 'SPECIAL', "sigla" => 'GI', 'it' =>	'160° anniversario 2° Guerra Indipendenza', 'en' =>	'160th Anniversary 2nd Italian Independence War'),
     array( 'gruppo' => 'SPECIAL', "sigla" => 'WWII', 'it' =>	'75° anniversario sbarco in Normandia', 'en' =>	'75th Anniversary D-Day'),
   );
?>
