<?php

$nations_array = array(
array('it' => 'Afghanistan', 'en' =>	'Afghanistan'),
array('it' => 'Albania', 'en' => 'Albania'),
array('it' => 'Algeria', 'en' =>	'Algeria'),
array('it' => 'Andorra', 'en' =>	'Andorra'),
array('it' => 'Angola', 'en' =>	'Angola'),
array('it' => 'Antigua e Barbuda', 'en' =>	'Antigua and Barbuda'),
array('it' => 'Arabia Saudita', 'en' =>	'Saudi Arabia'),
array('it' => 'Argentina', 'en' =>	'Argentina'),
array('it' => 'Armenia', 'en' =>	'Armenia'),
array('it' => 'Australia', 'en' =>	'Australia'),
array('it' => 'Austria', 'en' =>	'Austria'),
array('it' => 'Azerbaijan', 'en' =>	'Azerbaijan'),
array('it' => 'Bahamas', 'en' =>	'Bahamas'),
array('it' => 'Bahrain', 'en' =>	'Bahrain'),
array('it' => 'Bangladesh', 'en' =>	'Bangladesh'),
array('it' => 'Barbados', 'en' =>	'Barbados'),
array('it' => 'Belgio', 'en' =>	'Belgium'),
array('it' => 'Belize', 'en' =>	'Belize'),
array('it' => 'Benin', 'en' =>	'Benin'),
array('it' => 'Bhutan', 'en' =>	'Bhutan'),
array('it' => 'Bielorussia', 'en' =>	'Belarus'),
array('it' => 'Birmania', 'en' =>	'Myanmar'),
array('it' => 'Bolivia', 'en' =>	'Bolivia'),
array('it' => 'Bosnia-Erzegovina', 'en' =>	'Bosnia and Herzegovina'),
array('it' => 'Botswana', 'en' =>	'Botswana'),
array('it' => 'Brasile', 'en' =>	'Brazil'),
array('it' => 'Brunei', 'en' =>	'Brunei'),
array('it' => 'Bulgaria', 'en' =>	'Bulgaria'),
array('it' => 'Burkina Faso', 'en' =>	'Burkina Faso'),
array('it' => 'Burundi', 'en' =>	'Burundi'),
array('it' => 'Cambogia', 'en' =>	'Cambodia'),
array('it' => 'Camerun', 'en' =>	'Cameroon'),
array('it' => 'Canada', 'en' =>	'Canada'),
array('it' => 'Capo Verde', 'en' =>	'Cape Verde Islands'),
array('it' => 'Ciad', 'en' =>	'Chad'),
array('it' => 'Cile', 'en' =>	'Chile'),
array('it' => 'Cina', 'en' =>	'China'),
array('it' => 'Cipro', 'en' =>	'Cyprus'),
array('it' => 'Città del Vaticano', 'en' =>	'Vatican City'),
array('it' => 'Colombia', 'en' =>	'Colombia'),
array('it' => 'Comore', 'en' =>	'Comoros'),
array('it' => 'Congo', 'en' =>	'Congo'),
array('it' => 'Corea del Nord', 'en' =>	'North Korea'),
array('it' => 'Corea del Sud', 'en' =>	'South Korea'),
array('it' => 'Costa d\'Avorio', 'en' =>	'Ivory Coast'),
array('it' => 'Costa Rica', 'en' =>	'Costa Rica'),
array('it' => 'Croazia', 'en' =>	'Croatia'),
array('it' => 'Cuba', 'en' =>	'Cuba'),
array('it' => 'Danimarca', 'en' =>	'Denmark'),
array('it' => 'Dominica', 'en' =>	'Dominica'),
array('it' => 'Ecuador', 'en' =>	'Ecuador'),
array('it' => 'Egitto', 'en' =>	'Egypt'),
array('it' => 'El Salvador', 'en' =>	'El Salvador'),
array('it' => 'Emirati Arabi Uniti', 'en' =>	'The United Arab Emirates'),
array('it' => 'Eritrea', 'en' =>	'Eritrea'),
array('it' => 'Estonia', 'en' =>	'Estonia'),
array('it' => 'Etiopia', 'en' =>	'Ethiopia'),
array('it' => 'Fiji', 'en' =>	'Fiji'),
array('it' => 'Filippine', 'en' =>	'Philippines'),
array('it' => 'Finlandia', 'en' =>	'Finland'),
array('it' => 'Francia', 'en' =>	'France'),
array('it' => 'Gabon', 'en' =>	'Gabon'),
array('it' => 'Galles', 'en' =>	'Wales'),
array('it' => 'Gambia', 'en' =>	'Gambia'),
array('it' => 'Georgia', 'en' =>	'Georgia'),
array('it' => 'Germania', 'en' =>	'Germany'),
array('it' => 'Ghana', 'en' =>	'Ghana'),
array('it' => 'Giamaica', 'en' =>	'Jamaica'),
array('it' => 'Giappone', 'en' =>	'Japan'),
array('it' => 'Gibuti', 'en' =>	'Djibouti'),
array('it' => 'Giordania', 'en' =>	'Jordan'),
array('it' => 'Gran Bretagna', 'en' =>	'Great Britain'),
array('it' => 'Grecia', 'en' =>	'Greece'),
array('it' => 'Grenada', 'en' =>	'Grenada'),
array('it' => 'Groenlandia', 'en' =>	'Greenland'),
array('it' => 'Guatemala', 'en' =>	'Guatemala'),
array('it' => 'Guinea', 'en' =>	'Guinea'),
array('it' => 'Guinea Equatoriale', 'en' =>	'Equatorial Guinea'),
array('it' => 'Guinea-Bissau', 'en' =>	'Guinea-Bissau'),
array('it' => 'Guyana', 'en' =>	'Guyana'),
array('it' => 'Haiti', 'en' =>	'Haiti'),
array('it' => 'Honduras', 'en' =>	'Honduras'),
array('it' => 'Hongkong', 'en' =>	'Hong Kong'),
array('it' => 'India', 'en' =>	'India'),
array('it' => 'Indonesia', 'en' =>	'Indonesia'),
array('it' => 'Inghilterra', 'en' =>	'England'),
array('it' => 'Iran', 'en' =>	'Iran'),
array('it' => 'Iraq', 'en' =>	'Iraq'),
array('it' => 'Irlanda', 'en' =>	'Ireland'),
array('it' => 'Irlanda del Nord', 'en' =>	'Northern Ireland'),
array('it' => 'Islanda', 'en' =>	'Iceland'),
array('it' => 'Isole Faroe', 'en' =>	'Faroe Islands'),
array('it' => 'Isole Marshall', 'en' =>	'Marshall Islands'),
array('it' => 'Isole Salomone', 'en' =>	'Solomon Islands'),
array('it' => 'Israele', 'en' =>	'Israel'),
array('it' => 'Italia', 'en' =>	'Italy'),
array('it' => 'Kazakistan', 'en' =>	'Kazakhstan'),
array('it' => 'Kenya', 'en' =>	'Kenya'),
array('it' => 'Kirghizistan', 'en' =>	'Kyrgystan'),
array('it' => 'Kiribati', 'en' =>	'Kiribati'),
array('it' => 'Kosovo', 'en' =>	'Kosovo'),
array('it' => 'Kuwait', 'en' =>	'Kuwait'),
array('it' => 'Laos', 'en' =>	'Laos'),
array('it' => 'Lesotho', 'en' =>	'Lesotho'),
array('it' => 'Lettonia', 'en' =>	'Latvia'),
array('it' => 'Libano', 'en' =>	'Lebanon'),
array('it' => 'Liberia', 'en' =>	'Liberia'),
array('it' => 'Libia', 'en' =>	'Libya'),
array('it' => 'Liechtenstein', 'en' =>	'Liechtenstein'),
array('it' => 'Lituania', 'en' =>	'Lithuania'),
array('it' => 'Lussemburgo', 'en' =>	'Luxembourg'),
array('it' => 'Macao', 'en' =>	'Macao'),
array('it' => 'Macedonia', 'en' =>	'Macedonia'),
array('it' => 'Madagascar', 'en' =>	'Madagascar'),
array('it' => 'Malawi', 'en' =>	'Malawi'),
array('it' => 'Maldive', 'en' =>	'The Maldives'),
array('it' => 'Malesia', 'en' =>	'Malaysia'),
array('it' => 'Mali', 'en' =>	'Mali'),
array('it' => 'Malta', 'en' =>	'Malta'),
array('it' => 'Marocco', 'en' =>	'Morocco'),
array('it' => 'Mauritania', 'en' =>	'Mauritania'),
array('it' => 'Mauritius', 'en' =>	'Mauritius'),
array('it' => 'Messico', 'en' =>	'Mexico'),
array('it' => 'Micronesia', 'en' =>	'Micronesia'),
array('it' => 'Moldavia', 'en' =>	'Moldova'),
array('it' => 'Monaco', 'en' =>	'Monaco'),
array('it' => 'Mongolia', 'en' =>	'Mongolia'),
array('it' => 'Montenegro', 'en' =>	'Montenegro'),
array('it' => 'Mozambico', 'en' =>	'Mozambique'),
array('it' => 'Namibia', 'en' =>	'Namibia'),
array('it' => 'Nauru', 'en' =>	'Nauru'),
array('it' => 'Nepal', 'en' =>	'Nepal'),
array('it' => 'Nicaragua', 'en' =>	'Nicaragua'),
array('it' => 'Niger', 'en' =>	'Niger'),
array('it' => 'Nigeria', 'en' =>	'Nigeria'),
array('it' => 'Norvegia', 'en' =>	'Norway'),
array('it' => 'Nuova Zelanda', 'en' =>	'New Zealand'),
array('it' => 'Oman', 'en' =>	'Oman'),
array('it' => 'Paesi Bassi', 'en' =>	'Netherlands'),
array('it' => 'Pakistan', 'en' =>	'Pakistan'),
array('it' => 'Palau', 'en' =>	'Palau'),
array('it' => 'Palestina', 'en' =>	'Palestine'),
array('it' => 'Panama', 'en' =>	'Panama'),
array('it' => 'Papua-Guinea', 'en' =>	'Papua New Guinea'),
array('it' => 'Paraguay', 'en' =>	'Paraguay'),
array('it' => 'Perù', 'en' =>	'Peru'),
array('it' => 'Polonia', 'en' =>	'Poland'),
array('it' => 'Porto Rico', 'en' =>	'Puerto Rico'),
array('it' => 'Portogallo', 'en' =>	'Portugal'),
array('it' => 'Qatar', 'en' =>	'Qatar'),
array('it' => 'Regno unito', 'en' =>	'United Kingdom'),
array('it' => 'Repubblica Ceca', 'en' =>	'Czech Republic'),
array('it' => 'Repubblica Centrafricana', 'en' =>	'Central African Republic'),
array('it' => 'Repubblica democratica del Congo', 'en' =>	'Democratic Republic of Congo'),
array('it' => 'Repubblica Dominicana', 'en' =>	'Dominican Republic'),
array('it' => 'Romania', 'en' =>	'Romania'),
array('it' => 'Ruanda', 'en' =>	'Rwanda'),
array('it' => 'Russia', 'en' =>	'Russia'),
array('it' => 'Samoa', 'en' =>	'Samoa'),
array('it' => 'San Marino', 'en' =>	'San Marino'),
array('it' => 'Santa Lucia', 'en' =>	'St Lucia'),
array('it' => 'Scozia', 'en' =>	'Scotland'),
array('it' => 'Senegal', 'en' =>	'Senegal'),
array('it' => 'Serbia', 'en' =>	'Serbia'),
array('it' => 'Seychelles', 'en' =>	'Seychelles'),
array('it' => 'Sierra Leone', 'en' =>	'Sierra Leone'),
array('it' => 'Singapore', 'en' =>	'Singapore'),
array('it' => 'Siria', 'en' =>	'Syria'),
array('it' => 'Slovacchia', 'en' =>	'Slovakia'),
array('it' => 'Slovenia', 'en' =>	'Slovenia'),
array('it' => 'Somalia', 'en' =>	'Somalia'),
array('it' => 'Spagna', 'en' =>	'Spain'),
array('it' => 'Sri Lanka', 'en' =>	'Sri Lanka'),
array('it' => 'Stati Uniti d\'America', 'en' =>	'Unites States of America'),
array('it' => 'Sud Africa', 'en' =>	'South Africa'),
array('it' => 'Sudan', 'en' =>	'Sudan'),
array('it' => 'Suriname', 'en' =>	'Suriname'),
array('it' => 'Svezia', 'en' =>	'Sweden'),
array('it' => 'Svizzera', 'en' =>	'Switzerland'),
array('it' => 'Swasiland', 'en' =>	'Swaziland'),
array('it' => 'São Tomé e Príncipe', 'en' =>	'São Tomé and Príncipe'),
array('it' => 'Tailandia', 'en' =>	'Thailand'),
array('it' => 'Taiwan', 'en' =>	'Taiwan'),
array('it' => 'Tajikistan', 'en' =>	'Tajikistan'),
array('it' => 'Tanzania', 'en' =>	'Tanzania'),
array('it' => 'Tibet', 'en' =>	'Tibet'),
array('it' => 'Timor Est', 'en' =>	'East Timor'),
array('it' => 'Togo', 'en' =>	'Togo'),
array('it' => 'Tonga', 'en' =>	'Tonga'),
array('it' => 'Trinidad e Tobago', 'en' =>	'Trinidad and Tobago'),
array('it' => 'Tunisia', 'en' =>	'Tunisia'),
array('it' => 'Turchia', 'en' =>	'Turkey'),
array('it' => 'Turkmenistan', 'en' =>	'Turkmenistan'),
array('it' => 'Tuvalu', 'en' =>	'Tuvalu'),
array('it' => 'Ucraina', 'en' =>	'Ukaraine'),
array('it' => 'Uganda', 'en' =>	'Uganda'),
array('it' => 'Ungheria', 'en' =>	'Hungary'),
array('it' => 'Uruguay', 'en' =>	'Uruguay'),
array('it' => 'Uzbekistan', 'en' =>	'Uzbekistan'),
array('it' => 'Vanuatu', 'en' =>	'Vanuatu'),
array('it' => 'Venezuela', 'en' =>	'Venezuela'),
array('it' => 'Vietnam', 'en' =>	'Vietnam'),
array('it' => 'Yemen', 'en' =>	'Yemen'),
array('it' => 'Zambia', 'en' =>	'Zambia'),
array('it' => 'Zimbabwe', 'en' =>	'Zimbabwe')
);


?>
